### ISSUE TITLE
Amend the Decred Constitution

### ISSUE THREAD

**Issue by noahpierau** [decredcommunity/issues#107]
There seems to be social consensus that we should amend the constitution. 

This is the rough process: 
1) discuss scope and nature of amendment.
2) post about a tentative plan to [/r/decred](https://www.reddit.com/r/decred/).
3) open docs PR that amends the [constitution](https://docs.decred.org/governance/decred-constitution/). 
4) submit [Politeia](https://proposals.decred.org/) proposal to ratify amendment.

Active PR: https://github.com/decred/dcrdocs/pull/860

Discussions:

* [2019-02-11](https://matrix.to/#/!kdpEDksmOMNrlMqffD:decred.org/$15499080166701fVXhx:decred.org): remove the relic councils, they are confusing and might turn people off
* [2019-02-11](https://matrix.to/#/!tIDEIWechmqCLjPiui:decred.org/$15499153846889qdXsB:decred.org): it should be more of an amendment than re-writing, mainly to remove legacy stuff and add important new stuff (like the role of Politeia)
* [2019-02-16](https://github.com/decred/dcrdocs/pull/860): first draft posted on dcrdocs
* [2019-02-16](https://matrix.to/#/!tIDEIWechmqCLjPiui:decred.org/$155028022413273gpXUM:decred.org): first draft; larger changes: missing conflict resolution strategy in case different guiding principles are in conflict, fixed supply is not a necessary condition for SoV, non-binding nature of the constitution
* [2019-02-18](https://www.reddit.com/r/decred/comments/arry2z/proposing_an_amendment_to_the_decred_constitution/): post on Reddit called "Proposing an amendment to the Decred constitution" with a discussion on whether a Decred constitution is necessary or not, and what its purpose should be
* [2019-02-20](https://www.reddit.com/r/decred/comments/asnl21/should_we_scrap_the_decred_constitution/): post on Reddit called "Should we scrap the Decred constitution?" with feedback on the current draft
* [2019-04-05](https://proposals.decred.org/proposals/fd56bb79e0383f40fc2d92f4473634c59f1aa0abda7aabe29079216202c83114): Politeia proposal submitted

**Comment by xaur** [comment]
The proposal can ratify both the amendment (diff) and the full amended version. Noting this since there was no voting to ratify the initial constitution. Doing both in one go is nice.

**Comment by Dustorf** [comment]
I think that's a good idea, xaur. It looks to me like the only two areas in need of amending are project governance and funding. LMK if you agree.

**Comment by xaur** [comment]
Need to check the discussion, but I remember there were some incorrect bits that need to be removed. Pinging @RichardRed0x since he suggested the idea to ratify constitution on Politeia.

Since the proposal will be to amend the constitution document, it will be nice if complete information about the change is recorded in the resilient Politeia file system.

Complete information includes:

1. text of the proposal
2. old constitution doc
3. new constitution doc

This way both old and new constitution are ratified and stored forever in Politeia. In Markdown format, they are very light (a few kilobytes each). The two docs can be diffed to view only the change.

Need to clarify if Politeia allows to attach a second Markdown file.

Whoever picks the writing, I recommend to put pre-proposal (and possible accompanying old and new constitution files) in a gist, and share the link everywhere.

_P.S. man I wish nation state laws were handled like this, written in Markdown, stored and versioned in Git! Let's set a decent example.

**Comment by RichardRed0x** [comment]
Good suggestions @xaur .
Markdown attachments are not allowed, only png and txt. Having the old and new versions and diff on Pi is a nice idea though.
The document is such that having markdown in a txt file would probably not be too bad (just some * and ##, no links that really screw with reading markdown as txt).

I agree that that's where the changes are @Dustorf 

If there is consensus that what we want for now is an amendment which removes old inaccurate information and adds statements about missing things (like Politeia), I would be up for taking on the role of shepherding this along.

**Comment by Dustorf** [comment]
+1 on Richard taking a first crack on this and then we can review and discuss

**Comment by xaur** [comment]
As txt it would work fine, like any "lightweight markup" markdown is human readable in raw form. The key is that the files will be anchored and stored in a super simple format that can be read on any device. I would suggest some extra restrictions for such files: ASCII-only charset, no [BOM](https://en.wikipedia.org/wiki/Byte_order_mark), LF line endings.

**Comment by RichardRed0x** [comment]
Thoughts on this as I'm drafting it:

- I did make minor edits to Introduction, Principles and Blockchain Governance.
- Blockchain Governance section could say more about the consensus rules voting procedure, I added one sentence but it could go into much more detail in my opinion, or link to the relevant page.
- The best way to share the new draft is probably opening a WIP PR to dcrdocs, because that will generate a diff that people can see in browsers to follow the changes - it is also a good way to collect feedback.

**Comment by noahpierau** [comment]
Edits to the Introduction and Blockchain Governance sections look good! I personally think that we could have less detail in the Blockchain Governance section and link to relevant pages of the docs instead. We also need to think more carefully about the Project Governance and Funding section. What information is necessary to include in each point? How can we present these points in a logical order? All in all, this is a great starting point. Thank you for taking the initiative @RichardRed0x

**Comment by xaur** [comment]
Updated issue description to include discussions. You can see past versions by clicking "edited..." down arrow.

**Comment by noahpierau** [comment]
After this comment I haven't seen much action around the constitution discussion: https://www.reddit.com/r/decred/comments/asnl21/should_we_scrap_the_decred_constitution/egwfo3a

Shall we just open a PR for the latest version and put it up for vote on Politeia?

**Comment by xaur** [comment]
@noahpierau there is a [PR open](https://github.com/decred/dcrdocs/pull/860) in dcrdocs and some discussion.

I'm not up to date on all discussions that took place, but in any case I support the idea to update the constitution while trying to minimize the diff. The immediate benefit is a constitution up to date with current state of things and less confusion. Ditching it entirely is a more radical move that should be voted separately.

+1 to post on Politeia, it would push the issue further. Also, based on feedback there new iterations of the draft can be made.

I suggest that first revision of the proposal attaches existing constitution and first draft of its amended version as text files. Any revisions of the proposal should attach updated draft of the amended version. This way all drafts are recorded on Politeia properly and can be diffed.

@lukebp does Politeia handle updates of attached files in proposal revisions? By handle I mean allow to overwrite existing attachment and store both old and new version of the attachment in Git.

**Comment by lukebp** [comment]
> does Politeia handle updates of attached files in proposal revisions? By handle I mean allow to overwrite existing attachment and store both old and new version of the attachment in Git.

Yes.

**Comment by xaur** [comment]
Noticed you didn't use attachments in the proposal @RichardRed0x, were there any problems with them?

**Comment by RichardRed0x** [comment]
There is an issue with markdown files (or any text files) being attached to proposals. Even one is too many. This [PR](https://github.com/decred/politeia/pull/709) should address it, but it is not yet merged.

**Comment by xaur** [comment]
https://github.com/decred/dcrdocs/pull/860 is merged and the new constitution [is live](https://docs.decred.org/governance/decred-constitution/). Thanks all! Closing.
