### ISSUE TITLE
UI for dcrtime

### ISSUE THREAD

**Issue by xaur** [decredcommunity/issues#9]
Discussed here: https://matrix.to/#/!MIGqWXfLFBwhipPKYL:decred.org/$154377139031104yJIOS:decred.org

@degeri started hacking on it.

Close this issue when: there exist a simple UI to timestamp files.

**Comment by xaur** [comment]
Related effort: https://github.com/getset0/authit , chat discussion [here](https://matrix.to/#/!MIGqWXfLFBwhipPKYL:decred.org/$154401401634170cKmJY:decred.org).

**Comment by degeri** [comment]
looping in @fernandoabolafio and @tiagoalvesdulce

Also wanted to know will https://github.com/getset0/authit be a decred project or personal ?

**Comment by fernandoabolafio** [comment]
@degeri Although it started with the intention to create a personal project, now I would love to see it as a Decred project. I think we can structure to create an application that can support a variety of authentication services by using the Dcrtime and Politeia as backend.  Anyhow, starting by having a GUI for Dcrtime is a sweet start point.

**Comment by xaur** [comment]
From another [discussion](https://matrix.to/#/!MIGqWXfLFBwhipPKYL:decred.org/$154454253739832PpXgR:decred.org):

> Hey guys, as we have discussed here before we managed to create the very first version for Dcrtime: https://authit.co/  
> We had plans to extend the Dcrtime functionality and make it a personal project before. However as we saw great interest from the community we want it to be a Decred project so we can grow it following the community vision and feedbacks.  
> If that’s look good we can move the repository into Decred repositories and also host the website in the Decred servers. (fernandoabolafio)

**Comment by xaur** [comment]
Another web UI for dcrtime:

http://www.ibitlin.com/dcrtool#/dcrtime

Introduced in a Chinese [blog post](https://teakki.com/p/5c774a9ab1029f607605bc76), thanks @Guang168 for info.

**Comment by xaur** [comment]
Authit was renamed to [dcrtimegui](https://github.com/decred/dcrtimegui), moved under decred GitHub org and deployed at [timestamp.decred.org](https://timestamp.decred.org/). Thanks to the developers! Closing.
